default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: vscode
  password:

development:
  <<: *default
  database: money_math_lab_development

test:
  <<: *default
  database: money_math_lab_test

production:
  <<: *default
  database: money_math_lab_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
